version: '3.8'

services:
  nginx:
    image: nginx:latest
    container_name: my_ngnix
    ports:
      - "9000:80"
    volumes:
      - ./nginx:/etc/nginx/conf.d
    depends_on:
      - db
    networks:
      - app-network

  db:
    image: postgres:latest
    container_name: my_db
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: db
    volumes:
      - db-data:/var/lib/postgresql/data  # Persistent volume for DB data
    ports:
      - "8432:5432" 
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  db-data:
    driver: local
